AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - node_modules/node-sass/src/libsass/contrib/libsass.spec
    - config/initializers/devise.rb
    - node_modules/node-sass/src/libsass/extconf.rb
    

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
